# Site
name: "Lucas Limeira's Dev Blog"
title: "Lucas Limeira's Dev Blog"
description: "Tips and random posts from a developer to developers"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  lucas:
    name: Lucas Limeira
    description: 'Software Developer'
    display_name: Lucas Limeira
    gravatar: 3c8bd1df5f155df08805643ed18dc586 
    email: lucas@limeira.dev
    web: https://blog.limeira.dev

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enable"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
